services:
  kitchen-postgres:
    image: postgres:16
    container_name: kitchen-postgres
    environment:
      POSTGRES_DB: kitchen_db
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - kitchen_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - farmacyfood-net

  kitchen-service:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        MODULE: kitchen-service
    container_name: kitchen-service
    depends_on:
      - kitchen-postgres
    ports:
      - "7084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: >-
        -Dspring.datasource.url=jdbc:postgresql://kitchen-postgres:5432/kitchen_db?TimeZone=UTC
        -Deureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
        -Dclients.user-service.url=http://user-service:8086
        -Dclients.order-service.url=http://order-service:8083
        -Dclients.fridge-service.url=http://fridge-service:8082
    networks:
      - farmacyfood-net

volumes:
  kitchen_postgres_data:
