services:
  fridge-postgres:
    image: postgres:16
    container_name: fridge-postgres
    environment:
      POSTGRES_DB: fridge_db
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: UTC
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - fridge_postgres_data:/var/lib/postgresql/data
    networks:
      - farmacyfood-net

  fridge-mongo:
    image: mongo:7
    container_name: fridge-mongo
    environment:
      MONGO_INITDB_DATABASE: fridge_db
    ports:
      - "27018:27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - fridge_mongo_data:/data/db
    networks:
      - farmacyfood-net

  fridge-service:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        MODULE: fridge-service
    container_name: fridge-service
    depends_on:
      - fridge-postgres
      - fridge-mongo
    ports:
      - "7082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: >-
        -Dspring.datasource.url=jdbc:postgresql://fridge-postgres:5432/fridge_db?TimeZone=UTC
        -Dspring.data.mongodb.uri=mongodb://fridge-mongo:27017/fridge_db
        -Deureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
        -Dclients.kitchen-service.url=http://kitchen-service:8084
        -Dclients.notification-service.url=http://notification-service:8087
    networks:
      - farmacyfood-net

volumes:
  fridge_postgres_data:
  fridge_mongo_data:
