services:
  fridge-postgres:
    image: postgres:16
    container_name: fridge-postgres
    environment:
      POSTGRES_DB: fridge_db
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: UTC
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - fridge_postgres_data:/var/lib/postgresql/data

  fridge-mongo:
    image: mongo:7
    container_name: fridge-mongo
    environment:
      MONGO_INITDB_DATABASE: fridge_db
    ports:
      - "27018:27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - fridge_mongo_data:/data/db

volumes:
  fridge_postgres_data:
  fridge_mongo_data:
