server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Ruta especifica: matricular estudiante en carrera (msvc-carreras)
        - id: matricular
          uri: http://localhost:8002
          predicates:
            - Path=/api/estudiantes/*/carreras/**

        # Ruta especifica: buscar estudiantes por carrera+ciudad (msvc-carreras)
        - id: estudiantes-por-carrera
          uri: http://localhost:8002
          predicates:
            - Path=/api/estudiantes/carrera/**

        # Todas las rutas de carreras (msvc-carreras)
        - id: msvc-carreras
          uri: http://localhost:8002
          predicates:
            - Path=/api/carreras/**

        # Rutas generales de estudiantes (msvc-estudiantes) — debe ir ultima
        - id: msvc-estudiantes
          uri: http://localhost:8001
          predicates:
            - Path=/api/estudiantes/**
