server:
  port: 8088

spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:postgresql://localhost:5438/audit_db
    username: root
    password:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
    open-in-view: false
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /api/v1/auditoria/v3/api-docs

logging:
  level:
    com.farmacyfood.audit: INFO
