server:
  port: 8082

spring:
  application:
    name: fridge-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /api/v1/heladeras/v3/api-docs
