server:
  port: 8087

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://localhost:27019/notification_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

audit:
  service-name: NOTIFICATION-SERVICE

springdoc:
  api-docs:
    path: /api/v1/notificaciones/v3/api-docs

jwt:
  secret: clave.super.secreta.jwt.1234567890

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      pushService:
        baseConfig: default
