server:
  port: 8085

spring:
  application:
    name: recommendation-service
  profiles:
    active: prod

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /api/v1/recomendaciones/v3/api-docs

clients:
  user-service:
    url: http://localhost:8086
  order-service:
    url: http://localhost:8083
  product-service:
    url: http://localhost:8081

jwt:
  secret: clave.super.secreta.jwt.1234567890
