server:
  port: 8085

spring:
  application:
    name: recommendation-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /api/v1/recomendaciones/v3/api-docs
