-- ============================================================================
-- INIT SCRIPT — Audit Service (PostgreSQL)
-- ============================================================================
-- Este script: (1) crea la tabla si no existe, (2) agrega índices, y
-- (3) inserta datos de prueba para desarrollo.
--
-- Observación: JPA (ddl-auto: update) también crea la tabla automáticamente.
-- Este script actúa como fallback/referencia y garantiza que el esquema
-- esté presente incluso si JPA no gestiona el DDL.
-- ============================================================================

-- ─── 1. CREACIÓN DE TABLA ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS auditoria_eventos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name    VARCHAR(50)  NOT NULL,
    entity_type     VARCHAR(50)  NOT NULL,
    entity_id       VARCHAR(100) NOT NULL,
    action          VARCHAR(50)  NOT NULL,
    performed_by    VARCHAR(100),
    details         TEXT,
    timestamp       TIMESTAMP    NOT NULL DEFAULT NOW(),
    ip_address      VARCHAR(45),
    correlation_id  VARCHAR(100)
);

-- ─── 2. ÍNDICES ───────────────────────────────────────────────────────────
-- Mejoran la performance de las consultas más frecuentes.

CREATE INDEX IF NOT EXISTS idx_auditoria_service_name
    ON auditoria_eventos (service_name);

CREATE INDEX IF NOT EXISTS idx_auditoria_entity
    ON auditoria_eventos (entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_auditoria_action
    ON auditoria_eventos (action);

CREATE INDEX IF NOT EXISTS idx_auditoria_timestamp
    ON auditoria_eventos (timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_auditoria_correlation_id
    ON auditoria_eventos (correlation_id);

CREATE INDEX IF NOT EXISTS idx_auditoria_performed_by
    ON auditoria_eventos (performed_by);

-- ─── 3. DATOS DE PRUEBA (Solo si la tabla está vacía) ─────────────────────

INSERT INTO auditoria_eventos (service_name, entity_type, entity_id, action, performed_by, details, timestamp, ip_address, correlation_id)
SELECT * FROM (VALUES
    ('product-service', 'PRODUCT', '1', 'CREATE', 'admin@farmacyfood.com',
     '{"name":"Brownie de Chocolate","price":2500.00,"catalogoId":1}', NOW() - INTERVAL '2 days', '192.168.1.10', 'corr-001'),
    ('product-service', 'PRODUCT', '2', 'CREATE', 'admin@farmacyfood.com',
     '{"name":"Cheesecake de Frambuesa","price":3200.00,"catalogoId":1}', NOW() - INTERVAL '2 days', '192.168.1.10', 'corr-001'),
    ('user-service', 'USER', '3', 'REGISTER', 'SYSTEM',
     '{"email":"carlos@example.com","name":"Carlos Lopez"}', NOW() - INTERVAL '1 day', '10.0.0.15', 'corr-002'),
    ('order-service', 'ORDER', '1', 'CREATE', '3',
     '{"total":8200.00,"fridgeId":1,"items":[{"productId":1,"quantity":2},{"productId":2,"quantity":1}]}', NOW() - INTERVAL '12 hours', '10.0.0.15', 'corr-003'),
    ('order-service', 'ORDER', '1', 'PAYMENT_CONFIRMED', 'SYSTEM',
     '{"paymentId":"pay-abc-123","method":"MERCADO_PAGO"}', NOW() - INTERVAL '11 hours', null, 'corr-003'),
    ('fridge-service', 'HELADERA', '1', 'STATUS_CHANGE', 'SYSTEM',
     '{"oldStatus":"ACTIVE","newStatus":"MAINTENANCE","reason":"Mantenimiento programado"}', NOW() - INTERVAL '6 hours', null, 'corr-004'),
    ('fridge-service', 'STOCK', '5', 'UPDATE', 'SYSTEM',
     '{"productId":7,"oldQuantity":15,"newQuantity":8,"delta":-7}', NOW() - INTERVAL '3 hours', null, 'corr-005'),
    ('kitchen-service', 'DAILY_PLAN', '1', 'CREATE', 'admin@farmacyfood.com',
     '{"date":"2026-06-26","cocinaId":1,"items":[{"productId":1,"suggestedQuantity":20},{"productId":2,"suggestedQuantity":15}]}', NOW() - INTERVAL '1 hour', '192.168.1.20', 'corr-006')
) AS v(service_name, entity_type, entity_id, action, performed_by, details, timestamp, ip_address, correlation_id)
WHERE NOT EXISTS (SELECT 1 FROM auditoria_eventos LIMIT 1);
