-- ============================================================================
-- INIT SCRIPT — Audit Service (PostgreSQL)
-- ============================================================================
-- Este script: (1) crea la tabla si no existe, (2) agrega índices, y
-- (3) inserta datos de prueba para desarrollo.
--
-- Observación: JPA (ddl-auto: update) también crea la tabla automáticamente.
-- Este script actúa como fallback/referencia y garantiza que el esquema
-- esté presente incluso si JPA no gestiona el DDL.
-- ============================================================================

-- --- 1. CREACIÓN DE TABLA ---------------------------------------------------

CREATE TABLE IF NOT EXISTS auditoria_eventos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name    VARCHAR(100) NOT NULL,
    event_type      VARCHAR(20)  NOT NULL DEFAULT 'INFO',
    action          VARCHAR(100) NOT NULL,
    message         TEXT,
    request         TEXT,
    response        TEXT,
    timestamp       TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- --- 2. ÍNDICES ------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_auditoria_service_name
    ON auditoria_eventos (service_name);

CREATE INDEX IF NOT EXISTS idx_auditoria_event_type
    ON auditoria_eventos (event_type);

CREATE INDEX IF NOT EXISTS idx_auditoria_action
    ON auditoria_eventos (action);

CREATE INDEX IF NOT EXISTS idx_auditoria_timestamp
    ON auditoria_eventos (timestamp DESC);

-- --- 3. DATOS DE PRUEBA (Solo si la tabla está vacía) -----------------------

INSERT INTO auditoria_eventos (service_name, event_type, action, message, request, response, timestamp)
SELECT * FROM (VALUES
    ('ORDER-SERVICE', 'SUCCESS', 'CREATE_ORDER', 'Orden creada exitosamente',
     '{"method":"POST","path":"/api/v1/ordenes","body":{"userId":3,"fridgeId":1,"items":[{"productId":1,"quantity":2},{"productId":2,"quantity":1}]}}',
     '{"status":201,"body":{"orderId":1,"total":8200.00,"status":"CREATED"}}',
     NOW() - INTERVAL '12 hours'),
    ('FRIDGE-SERVICE', 'SUCCESS', 'GET_STOCK', 'Stock consultado exitosamente',
     '{"method":"GET","path":"/api/v1/heladeras/1/stock"}',
     '{"status":200,"body":{"heladeraId":1,"items":[{"productId":1,"quantity":50},{"productId":2,"quantity":30}]}}',
     NOW() - INTERVAL '11 hours'),
    ('ORDER-SERVICE', 'SUCCESS', 'PAY_ORDER', 'Orden pagada exitosamente',
     '{"method":"PUT","path":"/api/v1/ordenes/1/pago","body":{"paymentMethod":"MERCADO_PAGO","paymentId":"pay-abc-123"}}',
     '{"status":200,"body":{"orderId":1,"status":"PAYMENT_CONFIRMED","total":8200.00}}',
     NOW() - INTERVAL '10 hours'),
    ('FRIDGE-SERVICE', 'INFO', 'UPDATE_FRIDGE', 'Heladera actualizada a mantenimiento',
     '{"method":"PATCH","path":"/api/v1/heladeras/1","body":{"status":"MAINTENANCE","reason":"Mantenimiento programado"}}',
     '{"status":200,"body":{"heladeraId":1,"oldStatus":"ACTIVE","newStatus":"MAINTENANCE"}}',
     NOW() - INTERVAL '6 hours'),
    ('KITCHEN-SERVICE', 'SUCCESS', 'GENERATE_DAILY_PLAN', 'Plan diario generado exitosamente',
     '{"method":"POST","path":"/api/v1/plan-diario","body":{"date":"2026-06-27","cocinaId":1,"items":[{"productId":1,"suggestedQuantity":20}]}}',
     '{"status":201,"body":{"planId":1,"date":"2026-06-27","status":"CREATED"}}',
     NOW() - INTERVAL '1 hour')
) AS v(service_name, event_type, action, message, request, response, timestamp)
WHERE NOT EXISTS (SELECT 1 FROM auditoria_eventos LIMIT 1);
