include:
  - path: ./product-service/docker-compose.yml
  - path: ./kitchen-service/docker-compose.yml
  - path: ./fridge-service/docker-compose.yml
  - path: ./order-service/docker-compose.yml
  - path: ./notification-service/docker-compose.yml
  - path: ./user-service/docker-compose.yml
