server:
  port: 8084

spring:
  application:
    name: kitchen-service
  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/kitchen_db?TimeZone=UTC
    username: root
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /api/v1/cocina-fantasma/v3/api-docs
  swagger-ui:
    path: /api/v1/cocina-fantasma/swagger-ui.html
  info:
    title: Cocina Fantasma API
    description: API del servicio de cocina fantasma para planificación de producción y gestión de catálogo
