server:
  port: 8084

spring:
  application:
    name: kitchen-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /api/v1/cocina/v3/api-docs
