server:
  port: 8081

spring:
  application:
    name: product-service
  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://localhost:5437/product_db?TimeZone=UTC
    username: root
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /api/v1/productos/v3/api-docs
