server:
  port: 8083

spring:
  application:
    name: order-service
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5434/order_db?TimeZone=UTC
    username: root
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /api/v1/ordenes/v3/api-docs

jwt:
  secret: clave.super.secreta.jwt.1234567890
  expiration-ms: 3600000
