services:
  mongo-notification:
    image: mongo:7
    container_name: notification-mongo
    environment:
      MONGO_INITDB_DATABASE: notification_db
    ports:
      - "27019:27017"
    volumes:
      - notification_mongo_data:/data/db

volumes:
  notification_mongo_data:
