services:
  mongo-notification:
    image: mongo:7
    container_name: farmacyfood_mongo_notification
    environment:
      MONGO_INITDB_DATABASE: farmacyfood_notification
    ports:
      - "27017:27017"
    volumes:
      - mongo_notification_data:/data/db

volumes:
  mongo_notification_data:
